# The URL the site will be built for
base_url = "https://innocentuslime.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "css"

[extra]
zola_version = "0.19.2"
content_license_name = "CC BY 4.0"
content_license_link = "https://creativecommons.org/licenses/by/4.0/"