name: Build and deploy the vue
on:
  push:
    branches:
      - 'main'

jobs:
  build_deploy_vue:
    runs-on: ubuntu-latest
    name: Build and Deploy Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Deploy-Vue
      uses: LizAinslie/VueBuildToBranchAction@1.0.2 
      with:
        username: 'InnocentusLime'
        reponame: 'innocentuslime.github.io'
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'main'
